services:
  - type: web
    name: Portafolio_Jc
    env: python
    repo: https://github.com/JCARDONA1650/Portafolio_Jc.git
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn MI_PORTAFOLIO.wsgi:application --bind 0.0.0.0:8000"
