# Generated by Django 5.1.5 on 2025-03-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_portafolio', '0001_initial'),
    ]

    operations = [
    ]
